"""The neural band model: gamma dynamics, equilibria, and stability.

``NeuralBandModel`` is the model proper.  This file holds its core: the
coherence ODE ``dgamma_dt`` and its relaxation, the heading torque
``dtheta_dt``, the self-consistent and fixed-heading equilibrium finders, and
the two stability criteria built on the numerically-differenced 3x3 Jacobian.

Its rasters, basin wheels and walker ensemble are mixed in from ``_nbm_plots``,
``_nbm_basins`` and ``_nbm_walkers`` -- see the manifest in the class body.
"""

import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import root, brentq

from .angles import convert_angles
from .perception_model import PerceptionModel
from ._nbm_basins import _BasinMixin
from ._nbm_plots import _PlotMixin
from ._nbm_walkers import _WalkerMixin


class NeuralBandModel(_WalkerMixin, _BasinMixin, _PlotMixin):
    '''This class takes in a PerceptionModel and uses the neural angles and group 
    sizes to chose a consensus neural direction based on a discrete Ising 
    Hamiltonian. It then translates this into a consensus physical direction. 
    Relies on get_neural_signals from the PerceptionModel to obtain 
    neural angles and relative neural group size.

    Separation of timescales
    ------------------------
    As-written this class rests on the neural ring being FAST relative to
    the observer's turning: gamma is taken to sit at its equilibrium gamma*
    for the heading currently held, and the heading then moves under the
    torque that gamma* produces. `dgamma_dt` is not a first-principles
    equation of motion -- it is the rank-2 readout of the underlying Glauber
    population dynamics with the term generated by the observer's own turning
    dropped (see `_discrim_reduced`), so it is exact at dtheta/dt = 0 and
    valid off equilibrium only under that separation. Three consequences:

      * `dtheta_dt` runs `run_dgamma_dt` to steady state before reading the
        torque, and `plot_walkers` / `_basin_destination` re-equilibrate gamma
        at every heading step. The 'reduced' stability criterion is the
        matching linearization, which is why it is the default.
      * The choice of frame for gamma is therefore inert AT EQUILIBRIUM.
        This class carries gamma in the EGOCENTRIC/neural frame; the Sridhar 
        derivation carries gamma_allo = gamma*exp(i*theta) in the allocentric 
        frame. The two vector fields differ by an advection term 
        -i*(dtheta/dt)*gamma (Sridhar doesn't have this owing to the fact that 
        it does not express a continuous-time model of angular movement 
        dtheta/dt) that vanishes at every equilibrium, so equilibria and both 
        stability criteria are identical. That equivalence is what allows the 
        allocentric model to be expressed here as `angle_distortion_nu` with an 
        identity warp and uniform weight. It does NOT extend to the walker, 
        whose heading moves: there the frame decides how gamma is carried from 
        one step to the next, and the two conventions can commit to different 
        branches. See `plot_walkers`, "Carrying gamma between steps".
      * The equivalence is a statement about the decoupled dynamics only. Taking
        the full 3x3 eigenvalues of `_coupled_jacobian` would linearize an
        incomplete equation (and would not be frame-invariant).
    '''


    # Methods live in three mixins alongside the core below:
    #   _PlotMixin   (_nbm_plots)   plot_nu_cosine, plot_dtheta_dt,
    #                               plot_direction_mesh, plot_bifurcation_diagram
    #   _BasinMixin  (_nbm_basins)  basin_arcs_at_focal_loc, _overlay_basin_wheels
    #   _WalkerMixin (_nbm_walkers) plot_walkers, _simulate_one_walk
    # They hold no state of their own and override nothing; the dynamics,
    # equilibria and stability criteria that they all call are right here.

    def __init__(self, percep_model=None, beta=10, K=2,
                 angle_distortion_nu=None):
        '''From a PerceptionModel with its Targets object, establishes a model
        for chosing direction based on discrete Ising. Relies on get_neural_signals
        from the PerceptionModel to obtain neural angles and relative neural
        group size.

        Parameters
        ----------
        percep_model : PerceptionModel
            A PerceptionModel object (with its Targets object) that establishes
            the geometry of the scenario. If none is provided, a default one
            will be created. The PerceptionModel can be updated to obtain
            consensus directions for different layouts or focal locations/angles.
        beta : float
            Inverse neural temperature: the Boltzmann factor beta = E/(k_B*temp) 
            of the Glauber dynamics, where E is the energy scale of the Ising 
            Hamiltonian, k_B is the Boltzmann constant, and temp is the 
            temperature in Kelvin. Large beta is cold (low noise, sharp 
            commitment), small beta is hot (diffuse). Unlike T in the Sridhar 
            et al. model, the noise level is target-independent; to reproduce 
            the Sridhar et al. model, set beta = N_total/T.
        K : float
            Coupling strength for Kuramoto turning speed. Used in models of
            walkers only. Default of 2 in order to match sine argument of ego/2.
        angle_distortion_nu : float, optional
            Neural tuning exponent nu of the distorted cosine coupling kernel
            in Sridhar et al. (2021), their Eq. [2]: J(x) = cos(pi*(|x|/pi)**nu).
            LOWER nu gives a SHARPER (more locally excitatory) peak: 
            See `nu_cosine`. Keep this as None unless you want to reproduce the 
            Sridhar et al. (2021) model with its distorted cosine kernel. 
            Must be positive. Setting this to anything except None REQUIRES a 
            perception model with an identity warp and uniform weight; a 
            ValueError is raised otherwise, and if no percep_model is supplied 
            one of exactly that form is built. It is a validating property, so 
            the same checks run on later assignment (e.g. sweeping nu).

            Note: when nu != 1. The gamma-flow stops being a gradient flow (the 
            fast block is no longer symmetric), so the analytic free-energy 
            Hessian does not apply and `_discrim_A` switches to the numerical 
            fast block. The default `_discrim_reduced` criterion is numerical 
            and stays valid. Also, this case carries the target-independent
            `beta` rather than the visible-target-count factor 2*N_vis/T:
            set beta = N_total/T to reproduce that model. The results differ 
            only where a target is FULLY occluded, such as directly behind a blocker.
        '''

        self.beta = beta
        self.K = K

        if percep_model is None:
            if angle_distortion_nu is None:
                self.percep_model = PerceptionModel()
            else:
                # The nu kernel takes perceived angles at face value, so the
                # default companion is the identity warp with uniform weight --
                # the configuration the setter enforces on a supplied one.
                self.percep_model = PerceptionModel(neural_angle_dist=None,
                                                    angle_weight=None)
        else:
            assert isinstance(percep_model,PerceptionModel),\
            "percep_model must be a PerceptionModel object."
            self.percep_model = percep_model

        # Assigned last, and through the validating property below: the
        # setter checks the perception model, so it needs one to check.
        self.angle_distortion_nu = angle_distortion_nu

        # Initial gamma value with a small coherence strength of 1e-5.
        # Phase is 0 in neural angle space (corresponding to straight ahead).
        self.gamma = complex(1e-5)

        # Random number generator for certain processes within the class;
        #   Can seed here for reproducability.
        #seed = 3
        self.rng = np.random.default_rng()


    @property
    def angle_distortion_nu(self):
        """Exponent of the distorted cosine coupling kernel (see __init__ and
        `nu_cosine`), or None for the plain cosine.

        Validated on assignment as well as at construction, since setting it
        on an already-built model is the natural way to sweep it. It must be a
        positive real, and anything other than None requires the attached
        perception model to have an identity warp and uniform weight.

        The check runs against the perception model attached at the time of
        assignment. Replacing `percep_model` afterwards is not re-checked --
        re-assign nu (`m.angle_distortion_nu = m.angle_distortion_nu`) to
        re-validate against the new one.
        """
        return self._angle_distortion_nu

    @angle_distortion_nu.setter
    def angle_distortion_nu(self, value):
        if value is not None:
            try:
                value = float(value)
            except (TypeError, ValueError):
                raise TypeError(
                    "angle_distortion_nu must be a real number or None, got "
                    f"{value!r}.") from None
            if not np.isfinite(value) or value <= 0:
                # nu <= 0 is not a sharper kernel, it is a degenerate one:
                # (|x|/pi)**nu -> 1 for every x != 0 as nu -> 0, collapsing
                # J to the constant -1, and it diverges at x = 0 for nu < 0.
                raise ValueError(
                    "angle_distortion_nu must be a finite positive number "
                    f"(or None for the plain cosine kernel), got {value!r}.")
            pm = self.percep_model
            if not (pm.warp_name is None and pm.weight_name is None):
                raise ValueError(
                    "angle_distortion_nu requires a PerceptionModel with an "
                    "identity warp and uniform weight, i.e. "
                    "PerceptionModel(neural_angle_dist=None, "
                    f"angle_weight=None); got neural_angle_dist="
                    f"{pm.warp_name!r}, angle_weight={pm.weight_name!r}. The "
                    "nu kernel distorts the coupling strength between "
                    "perceived directions while a warp distorts the angles "
                    "themselves; composing them is not a defined model. Leave "
                    "angle_distortion_nu at None to use a warped or weighted "
                    "perception model.")
        self._angle_distortion_nu = value


    @property
    def _nu_active(self):
        """True when the coupling kernel is the distorted cosine rather than
        the plain one, i.e. `angle_distortion_nu` is set to something other
        than 1. Everything nu-specific keys off this, so nu=None and nu=1 both
        take the untouched cosine path bit-for-bit."""
        return (self.angle_distortion_nu is not None
                and self.angle_distortion_nu != 1)


    def nu_cosine(self, x):
        """Coupling kernel J(x) = cos(pi*(|x|/pi)**nu) of Sridhar et al.
        (2021) Eq. [2], the plain cos(x) when `angle_distortion_nu` is None
        or 1.

        The exponent acts on the angular SEPARATION between two perceived
        directions, moving where the coupling changes sign (from pi/2 at nu=1
        to pi*(1/2)**(1/nu) generally) without touching the exp(i*angle) phase
        that sets which direction gamma points. Lower nu is a sharper, more
        locally excitatory kernel.

        Unlike cos, this is NOT 2*pi-periodic -- |x| is taken as given, so
        e.g. nu_cosine(3.283) differs from nu_cosine(3.283 - 2*pi). Callers
        must hand it an argument already wrapped into [-pi, pi]
        (`convert_angles`); `dgamma_dt` does.

        Parameters
        ----------
        x : float or ndarray of float
            angular separation, wrapped into [-pi, pi].

        Returns
        -------
        float or ndarray of float : the coupling kernel at x, in [-1, 1].
        """
        if not self._nu_active:
            return np.cos(x)
        return np.cos(np.pi*(np.abs(x)/np.pi)**self.angle_distortion_nu)


    def dgamma_dt(self, t=None, gamma=None, focal_angle=None, focal_loc=None,
                  signals=None):
        '''Get the complex time derivative of gamma according to the
        Ising model. For use directly in ODE solvers.

        gamma is the coherence value of the neural band, which is a complex 
        number whose angle represents the current consensus direction and whose 
        magnitude (a value between 0 and 1) represents the coherence strength.

            dgamma/dt = sum_j rho_j exp(i*a_j) sigma(2*beta*R*J(a_j - Theta))
                        - gamma

        with a_j the neural angle of target j, Theta = arg(gamma), R = |gamma|,
        sigma the logistic function and J the coupling kernel cosine or 
        `nu_cosine` if `angle_distortion_nu` is set.

        Parameters
        ----------
        t : float, optional
            time variable for ODE solver compatibility. Not used.
        gamma : complex, optional
            current coherence value of the neural band.
            If None, use self.gamma.
        focal_angle : float, optional
            the current heading (angle) of the observer. If None, use 
            self.percep_model.focal_angle.
        focal_loc : array-like of length 2, optional
            (x,y) location of the observer. If None, use the 
            self.percep_model.focal_loc.
        signals : tuple of (neural_angles, rho), optional
            Precomputed neural angles and normalized group sizes for each 
            visible target (for when the heading is held fixed across evaluations).
            If None, compute them from the perception model.

        Returns
        -------
        dgamma_dt : complex
            time derivative of gamma according to the Ising model
        '''

        if gamma is None:
            gamma = self.gamma
        Theta = np.angle(gamma)
        R = np.abs(gamma)

        if signals is None:
            neur_angles, rho = self.percep_model.get_neural_signals(
                focal_angle, focal_loc)
        else:
            neur_angles, rho = signals
        if neur_angles.size == 0:
            return -gamma
        
        # Coupling of each perceived direction to the current consensus.
        # cos is 2*pi-periodic, so the plain kernel needs no wrapping; the nu
        # kernel is NOT (it reads |x| literally), so its argument has to be
        # wrapped into [-pi, pi] first -- see nu_cosine. Branching rather than
        # always calling nu_cosine keeps the nu-free path bit-identical and
        # skips the wrap it does not need.
        if self._nu_active:
            coupling = self.nu_cosine(convert_angles(neur_angles - Theta))
        else:
            coupling = np.cos(neur_angles - Theta)

        # Compute the sum over all target angles.
        # Suppress overflow warnings: they indicate R is too large and are 
        #   likely the result of whatever numerical algorithm is being used
        #   trying out a bad R value.
        with np.errstate(over='ignore'):
            summands = rho*np.exp(1j*neur_angles)/(1+np.exp(
                -2*self.beta*R*coupling))

        return np.sum(summands) - gamma


    def dgamma_dt_vec(self, gamma_vec, focal_angle=None, focal_loc=None):
        '''Wrapper around dgamma_dt for use in root finding for equilibria.
        
        Here, gamma_vec is a length 2 ndarray of real and imaginary parts 
        representing the complex coherence value of the neural band.

        Parameters
        ----------
        gamma_vec : length 2 ndarray of float
            current (complex) coherence value of the neural band.
        focal_angle : float, optional
            the current heading (angle) of the observer. If None, use 
            self.percep_model.focal_angle.
        focal_loc : array-like of length 2, optional
            (x,y) location of the observer. If None, use self.percep_model.focal_loc.

        Returns
        -------
        dgamma_dt_vec : length 2 ndarray of float
            complex time derivative of gamma according to the Ising model
        '''
        dgamma = self.dgamma_dt(None, gamma_vec[0] + 1j*gamma_vec[1], 
                                focal_angle, focal_loc)
        return np.array([dgamma.real, dgamma.imag])
    

    def _self_consistent_eq(self, x, focal_loc):
        '''System of equations for finding self-consistent equilibria.

        At a self-consistent equilibrium, the observer is facing the consensus
        direction (heading = allocentric consensus), which means the egocentric
        consensus angle is zero, and therefore Theta_neural = 0 (gamma is real
        positive). We solve dgamma_dt(R + 0j, theta, focal_loc) = 0 for both
        theta (the allocentric heading/consensus direction) and R (the coherence
        strength).

        Parameters
        ----------
        x : length 2 ndarray
            [theta, R] where theta is the allocentric heading and R is the
            coherence strength.
        focal_loc : array-like of length 2
            (x,y) location of the observer.

        Returns
        -------
        length 2 ndarray : [Re(dgamma_dt), Im(dgamma_dt)]
        '''
        theta, R = x
        gamma = R + 0j
        dg = self.dgamma_dt(gamma=gamma, focal_angle=theta, focal_loc=focal_loc)
        return np.array([dg.real, dg.imag])


    def _self_consistent_jac(self, x, focal_loc, h=1e-7):
        '''Central-difference Jacobian of `_self_consistent_eq`.

        Supplied to the `hybr` polish in `sc_equilib` to make root-finding
        equivariant under the theta -> -theta mirror. `_self_consistent_eq`
        is y-flip symmetric to ~1e-20 (negating theta negates only the
        imaginary residual), but hybr's *built-in* Jacobian uses one-sided
        forward differences whose positive `+h` step direction breaks that
        symmetry: the iterate trajectory from a start is then not the mirror
        of the trajectory from the sign-flipped start, so near a saddle-node
        the polish can converge to different members of the equilibrium pair
        at (x, y) vs (x, -y) -- visible as y-asymmetry in bifurcation diagrams
        that should be mirror-symmetric. A central difference perturbs both
        +h and -h, so it is invariant under theta -> -theta; with it the whole
        hybrj Newton/dogleg iteration is equivariant and the self-consistent
        equilibrium set is exactly mirror-symmetric. (The forward/backward
        dgamma_dt evaluations also make the Jacobian estimate second-order
        accurate, which the polish doesn't need but doesn't hurt.)

        Parameters
        ----------
        x : length 2 ndarray
            [theta, R] as in `_self_consistent_eq`.
        focal_loc : array-like of length 2
            (x,y) location of the observer.
        h : float, optional
            finite-difference step (default 1e-7).

        Returns
        -------
        2x2 ndarray : d[Re,Im] / d[theta, R]
        '''
        x = np.asarray(x, dtype=float)
        n = x.size
        J = np.empty((n, n))
        for i in range(n):
            step = np.zeros(n)
            step[i] = h
            f_plus = self._self_consistent_eq(x + step, focal_loc)
            f_minus = self._self_consistent_eq(x - step, focal_loc)
            J[:, i] = (f_plus - f_minus) / (2 * h)
        return J


    def gamma_equilib(self, focal_angle=None, focal_loc=None,
                      stability_criterion='reduced'):
        '''Find gamma equilibria of dgamma/dt at a fixed observer heading.

        Multistart root-finding seeded on the polar circle of radius 0.5.
        Treats the observer's heading as given (not solved-for) and finds
        gamma values that are equilibria of dgamma_dt at that heading.
        Useful for analyzing the gamma landscape as the observer rotates,
        but NOT the right tool for bifurcation diagrams in (x, y): see
        sc_equilib() for that.

        Parameters
        ----------
        focal_angle : float, optional
            The observer's heading. If None, use self.percep_model.focal_angle.
        focal_loc : array-like of length 2, optional
            (x,y) location of the observer. If None, use
            self.percep_model.focal_loc.
        stability_criterion : {'reduced', 'discrim_a'}
            'reduced' (default): timescale-separated test -- fast gamma block
              A Hurwitz AND slow Schur complement d - c A^{-1} b < 0. The
              criterion consistent with gamma slaved to equilibrium (see
              `_discrim_reduced`).
            'discrim_a': legacy 2x2 gamma-only discriminant (fast block only).

        Returns
        -------
        gamma_eqs : list of complex
            equilibrium gamma values at the fixed heading.
        stability : list of bool
            stability of each equilibrium.
        '''
        if focal_angle is True:
            raise TypeError(
                "gamma_equilib(focal_angle=True) is no longer supported; "
                "call sc_equilib(focal_loc=..., "
                "stability_criterion=...) instead to find self-consistent "
                "equilibria (heading = allocentric consensus direction).")
        if stability_criterion == 'reduced':
            stability_test = self._discrim_reduced
        elif stability_criterion == 'discrim_a':
            stability_test = self._discrim_A
        else:
            raise ValueError(
                f"stability_criterion must be 'reduced' or 'discrim_a', "
                f"got {stability_criterion!r}")
        if focal_angle is None:
            focal_angle = self.percep_model.focal_angle
        init_angles = np.linspace(-np.pi, np.pi-0.01)
        final_gammas = []
        stability = []
        # The heading is held fixed here, so every dgamma_dt evaluation in the
        # whole multistart -- all 50 hybr solves -- shares one perception
        # state; only the stability test steps off it (theta +- h). Memoizing
        # the signals collapses ~1400 identical recomputations to one.
        with self.percep_model.signal_cache():
            for angle in init_angles:
                init_gamma = np.array([0.5*np.cos(angle), 0.5*np.sin(angle)])
                sol = root(self.dgamma_dt_vec, init_gamma,
                           args=(focal_angle, focal_loc),
                           method='hybr', tol=1e-7)
                if sol.success:
                    gamma_eq = sol.x[0] + 1j*sol.x[1]
                    close_check = False
                    for existing_gamma in final_gammas:
                        if np.abs(gamma_eq - existing_gamma) < 0.01:
                            close_check = True
                            break
                    if not close_check:
                        final_gammas.append(gamma_eq)
                        stability.append(stability_test(
                            gamma_eq, focal_angle, focal_loc))
        return final_gammas, stability


    def sc_equilib(self, focal_loc=None, stability_criterion='reduced',
                   return_R=False):
        '''Find self-consistent equilibria where heading = consensus direction.

        A self-consistent equilibrium is a fixed point of the coupled
        (gamma_re, gamma_im, theta) system: the observer is facing its
        own consensus direction, so the egocentric consensus angle is zero
        and gamma = R + 0j in the neural frame. Solve
        dgamma_dt(R + 0j, theta, focal_loc) = 0 for both theta (the
        allocentric heading) and R (coherence strength).

        Use this for bifurcation diagrams in (x, y): it finds the physically
        meaningful equilibria of the coupled heading-consensus system.

        Strategy: scan Im(dgamma_dt) across theta at a probe R to find
        sign changes, use brentq to pin down candidate theta values, then
        polish each candidate with a 2D hybr root finder. The Jacobian is
        near-block-diagonal (Im depends mostly on theta, Re depends mostly
        on R), so the Im scan seeds theta well and hybr converges reliably.

        Parameters
        ----------
        focal_loc : array-like of length 2, optional
            (x,y) location of the observer. If None, use
            self.percep_model.focal_loc.
        stability_criterion : {'reduced', 'discrim_a'}
            'reduced' (default): timescale-separated ("block") test. Stable
              iff the fast gamma block A is Hurwitz (gamma-equilibrium branch
              attracting) AND the slow Schur complement
              lam_slow = d - c A^{-1} b < 0 (the slaved heading flow
              dtheta/dt = g(h(theta)) is stable). This is the criterion
              consistent with gamma run to equilibrium before each heading
              step -- the dynamics the walker actually integrates. There is
              deliberately no fully-coupled criterion; see `_discrim_reduced`.
            'discrim_a': legacy 2x2 gamma-only discriminant (the original
              `_discrim_A` test; the fast block alone). Retained for
              comparison plots.
        return_R : bool
            If True, also return the coherence R = |gamma| at each
            equilibrium (needed for (x, R) branch diagrams). Default False
            preserves the 2-tuple return.

        Returns
        -------
        angle_eqs : list of float
            allocentric heading at each self-consistent equilibrium.
        R_eqs : list of float
            coherence R at each equilibrium. ONLY returned if return_R=True
            (then the return is the 3-tuple (angle_eqs, R_eqs, stability)).
        stability : list of bool
            stability of each equilibrium.
        '''
        if stability_criterion == 'reduced':
            stability_test = self._discrim_reduced
        elif stability_criterion == 'discrim_a':
            stability_test = self._discrim_A
        else:
            raise ValueError(
                f"stability_criterion must be 'reduced' or 'discrim_a', "
                f"got {stability_criterion!r}")

        # theta is a solve variable here, not a constant, so the signals
        # cannot be hoisted -- but the same headings recur constantly: each
        # scan node is evaluated at all three probe radii, the hybr polish
        # revisits its iterates, and the residual check and stability test
        # land back on the converged theta. Memoizing on the exact state
        # removes those repeats (~60-70% of the perception calls) without
        # changing what is computed.
        with self.percep_model.signal_cache():
            theta_mesh = np.linspace(-np.pi, np.pi, 100)
            final_angles = []
            stability = []

            # Collect candidate theta seeds from sign changes in Im(dgamma_dt),
            # scanning at SEVERAL probe radii. A single probe (formerly R=0.5)
            # only "sees" equilibria whose R sits near it: near a saddle-node a
            # stable/unstable pair can sit at R~0.6 and produce NO Im
            # sign-change at R=0.5, so its stable member was silently dropped
            # -- undercounting the diagram and leaving a spurious no-commit
            # ("grey") basin where the slaved flow in fact commits to that
            # attractor. Pooling seeds over probe radii catches these; every
            # seed is still hybr-polished, residual-verified and deduped below,
            # so extra probes can only surface genuine equilibria, never
            # spurious ones. Each seed carries the probe R it was found at so
            # the polish starts near the right coherence.
            # Under the distorted kernel the equilibria migrate outward
            # (nu=0.5 puts them at R ~ 0.77-0.85), above every probe here, and
            # the Im scan then reports no sign change at all for them. One
            # extra high probe recovers those; it is added only when the nu
            # kernel is active so the plain-cosine path keeps its cost and its
            # results unchanged.
            if self._nu_active:
                probe_radii = (0.3, 0.5, 0.7, 0.85)
            else:
                probe_radii = (0.3, 0.5, 0.7)
            candidates = []   # (theta_seed, R_seed)
            for R_probe in probe_radii:
                imag_vals = np.array([self.dgamma_dt(
                    gamma=R_probe+0j, focal_angle=t,
                    focal_loc=focal_loc).imag for t in theta_mesh])
                for i in range(len(imag_vals)-1):
                    if imag_vals[i]*imag_vals[i+1] < 0:
                        try:
                            theta_c = brentq(
                                lambda t: self.dgamma_dt(
                                    gamma=R_probe+0j, focal_angle=t,
                                    focal_loc=focal_loc).imag,
                                theta_mesh[i], theta_mesh[i+1])
                            candidates.append((theta_c, R_probe))
                        except ValueError:
                            pass
            # Always include theta=0 and theta=+-pi as candidates since
            # Im(dgamma_dt) is often zero there by symmetry but the sign
            # change can be narrower than the mesh spacing.
            for theta_extra in [0.0, np.pi, -np.pi]:
                candidates.append((theta_extra, 0.5))

            # Polish each candidate with the 2D root finder
            final_Rs = []
            for theta_c, R_seed in candidates:
                sol = root(self._self_consistent_eq, [theta_c, R_seed],
                           args=(focal_loc,), method='hybr', tol=1e-10,
                           jac=self._self_consistent_jac)
                if not sol.success:
                    continue
                theta_eq = convert_angles(sol.x[0])
                R_eq = sol.x[1]

                if R_eq < 0.01 or R_eq > 1.0:
                    continue

                # Verify residual is small
                residual = self.dgamma_dt(gamma=R_eq+0j,
                                          focal_angle=theta_eq,
                                          focal_loc=focal_loc)
                if np.abs(residual) > 1e-4:
                    continue

                # Dedup by both theta and R: near a saddle-node bifurcation
                # two genuine equilibria can share a theta to within the
                # angular tolerance while differing in R, so theta alone is
                # not enough to distinguish them.
                close_idx = None
                for j, (existing_angle, existing_R) in enumerate(
                        zip(final_angles, final_Rs)):
                    angle_diff = np.abs(convert_angles(
                        theta_eq - existing_angle))
                    R_diff = np.abs(R_eq - existing_R)
                    if angle_diff < 0.02 and R_diff < 0.01:
                        close_idx = j
                        break
                gamma_eq = R_eq + 0j
                if close_idx is None:
                    final_angles.append(theta_eq)
                    final_Rs.append(R_eq)
                    stability.append(stability_test(
                        gamma_eq, theta_eq, focal_loc))
                elif not stability[close_idx]:
                    # The first-kept member of this near-coincident pair is
                    # UNSTABLE. Near a saddle-node a stable and an unstable
                    # equilibrium can collide to within the (angle, R) dedup
                    # tolerance even with the full (theta, R) test; which
                    # member is found first depends on the brentq candidate
                    # order, which REVERSES under the y-mirror, so keeping "the
                    # first" makes the survivor's stability -- and the stable
                    # count -- flip between (x, y) and (x, -y). Prefer the
                    # STABLE member (a mirror-invariant choice) so the count
                    # stays correct and y-symmetric.
                    if stability_test(gamma_eq, theta_eq, focal_loc):
                        final_angles[close_idx] = theta_eq
                        final_Rs[close_idx] = R_eq
                        stability[close_idx] = True

        if return_R:
            return final_angles, final_Rs, stability
        return final_angles, stability
    

    def convert_gamma(self, gamma):
        '''Convert a given neural gamma value to an egocentric physical coherence 
        angle and coherence strength.

        Parameters
        ----------
        gamma : complex or array of complex
            coherence value of the neural band

        Returns
        -------
        angle : float or array of float
            physical angle corresponding to the input gamma value
        R : float or array of float
            coherence strength corresponding to the input gamma value
        '''
        Theta = np.angle(gamma)
        R = np.abs(gamma)
        return self.percep_model.get_neural_angle_inverse(Theta), R


    def run_dgamma_dt(self, focal_angle=None, focal_loc=None, init_gamma=None,
                      t_Final=100, warn=True):
        '''Solve the dgamma/dt equation and look for solutions to approach a
        stable equilibrium for the neural band model. Uses LSODA solver from
        scipy with a real-valued reformulation so that stiff-capable solvers
        can be applied.

        init_gamma is the initial coherence value to start from. If None,
        it will start from self.gamma.

        Parameters
        ----------
        focal_angle : float, optional
            the current heading (angle) of the observer. If None, use
            self.percep_model.focal_angle.
        focal_loc : array-like of length 2, optional
            (x,y) location of the observer. If None, use the percep_model's
            focal_loc.
        init_gamma : complex float, optional
            initial coherence value. If None, use the model's current gamma value.
        t_Final : float, optional
            maximum total time for integration (default 100).

        Returns
        -------
        gamma_equilib : complex float
            Equilibrium gamma value reached by integration.
        '''

        if init_gamma is None:
            init_gamma = self.gamma

        # The heading is fixed for the whole integration, so the perception
        # signals are invariant: fetch them ONCE and reuse on every RHS
        # evaluation (the solver calls the RHS dozens of times per
        # relaxation). Exact (~1e-14) and ~9x faster than recomputing per
        # call -- speeds every caller, walkers included (dtheta_dt ->
        # run_dgamma_dt each heading step).
        signals = self.percep_model.get_neural_signals(focal_angle, focal_loc)

        # Reformulate the complex ODE as a real 2D system so that LSODA
        # (a stiff-capable solver) can be used. Near-zero Jacobian eigenvalues
        # in the slow manifold between equilibria make LSODA significantly
        # more efficient than explicit RK45 with restarted windows.
        def dgamma_real(t, y):
            gamma = y[0] + 1j*y[1]
            dg = self.dgamma_dt(t, gamma, focal_angle, focal_loc,
                                signals=signals)
            return [dg.real, dg.imag]

        y0 = [np.real(init_gamma), np.imag(init_gamma)]
        sol = solve_ivp(dgamma_real, [0, t_Final], y0, method='LSODA')

        result = sol.y[0,-1] + 1j*sol.y[1,-1]
        tol = 1e-4
        if warn and np.abs(self.dgamma_dt(None, result, focal_angle,
                                          focal_loc, signals=signals)) > tol:
            print("Warning: Integration may not have reached equilibrium.")
        return result


    def dtheta_dt(self, t=None, theta=None, gamma=None, focal_loc=None,
                  t_Final=100):
        '''Turning rate based on the neural band model coherence value.

        Runs dgamma_dt to steady state and returns the Kuramoto-style torque
        K*R*sin(Theta/2), where Theta = arg(gamma) is the neural consensus
        angle and R = |gamma|.

        Parameters
        ----------
        t : float, optional
            time variable for ODE solver compatibility. Not used.
        theta : float, optional
            current heading angle of the observer in allocentric coordinates.
            If None, use self.percep_model.focal_angle.
        gamma : complex float, optional
            Equilibrium coherence value from neural band. If None, it will be
            computed by solving dgamma_dt to t_Final (using run_dgamma_dt) and
            taking the final solution as an equilibrium value. The IC for
            run_dgamma_dt will be self.gamma, and self.gamma will be updated
            to the result. If a complex value is provided, it is used directly
            (no ODE solve).
        focal_loc : array-like of length 2, optional
            (x,y) location of the observer. If None, use the percep_model's
            focal_loc.
        t_Final : float, optional (default=100)
            final time for integration of dgamma_dt if gamma is None.
        '''
        if theta is None:
            theta = self.percep_model.focal_angle
        if gamma is None:
            self.gamma = self.run_dgamma_dt(focal_angle=theta, focal_loc=focal_loc,
                                             init_gamma=None, t_Final=t_Final)
            gamma = self.gamma
        # Half-angle torque in the NEURAL consensus angle Theta = arg(gamma).
        # Theta is the canonical [-pi, pi] coordinate (the warp maps the
        # facing-away heading to +-pi for every perception model), so the
        # "/2" normalization is perception-model-independent and the torque
        # is zero only when consensus is straight ahead (Theta=0) and maximal
        # +-K*R when consensus is directly behind (Theta=+-pi). The +-pi point
        # carries an intentional +K*R <-> -K*R jump discontinuity (the physical
        # left/right fork facing away), resolved by roundoff/noise. We use
        # arg(gamma) directly rather than its inverse-warped egocentric angle:
        # the turning law is then a direct function of gamma* with no
        # dependence on the perception model's inverse mapping.
        Theta = np.angle(gamma)
        R = np.abs(gamma)
        return self.K * R * np.sin(Theta/2)


    def _coupled_jacobian(self, gamma_star, focal_angle, focal_loc, h=1e-6):
        '''Central-difference 3x3 Jacobian of the coupled
        (gamma_re, gamma_im, theta) system at (gamma_star, focal_angle),
        with dtheta/dt = K*R*sin(arg(gamma)/2).

        Used by `_discrim_reduced`, which needs the fast gamma block A and
        the sign of det(J). NOTE: the FULL eigenvalues of this matrix are NOT
        a stability verdict for the model -- see `_discrim_reduced` for why.
        '''
        gr0 = float(gamma_star.real)
        gi0 = float(gamma_star.imag)
        th0 = float(focal_angle)

        def coupled_rhs(gr, gi, th):
            gamma = gr + 1j*gi
            dg = self.dgamma_dt(gamma=gamma, focal_angle=th,
                                focal_loc=focal_loc)
            R = np.abs(gamma)
            dth = self.K * R * np.sin(np.angle(gamma)/2)
            return np.array([dg.real, dg.imag, dth])

        J = np.zeros((3, 3))
        for k, (dr, di, dt) in enumerate([(h, 0, 0), (0, h, 0), (0, 0, h)]):
            f_plus = coupled_rhs(gr0+dr, gi0+di, th0+dt)
            f_minus = coupled_rhs(gr0-dr, gi0-di, th0-dt)
            J[:, k] = (f_plus - f_minus) / (2*h)
        return J


    def _discrim_reduced(self, gamma_star, focal_angle, focal_loc,
                         h=1e-6, tol=1e-8):
        '''Timescale-separated ("block") stability test: the criterion that
        is consistent with the slaved gamma dynamics used everywhere else in
        the model (mean-field neural ring, gamma run to equilibrium before
        each dtheta step in plot_walkers, no gamma-noise).

        Partition the coupled Jacobian J = [[A, b], [c, d]] with A the 2x2
        gamma block, b = d(dgamma)/dtheta, c = d(dtheta)/dgamma,
        d = d(dtheta)/dtheta. The equilibrium is stable iff BOTH:

          1. Fast layer -- the gamma-equilibrium branch gamma = h(theta) is
             attracting: A is Hurwitz (all eig(A) real-part < -tol). This is
             exactly what `_discrim_A` tests (analytically for the cosine
             kernel, numerically otherwise).
          2. Slow layer -- the slaved flow dtheta/dt = g(h(theta)) is stable:
             its linearization is the Schur complement of A in J,
                 lam_slow = d - c A^{-1} b,
             the leading (lambda->0) term of the exact eigenvalue equation
             lam = d - c (A - lam I)^{-1} b; setting lambda = 0 inside the
             resolvent is exactly the adiabatic elimination of gamma. We need
             only its SIGN, which we read off without inverting A: by the
             block-determinant identity det(J) = det(A) * lam_slow, and
             det(A) > 0 for a Hurwitz 2x2 A, so
                 lam_slow < 0   <=>   det(J) < 0.
             Using det(J) keeps the slow test well-conditioned near a
             gamma-fold (eig(A) -> 0), where the Schur complement itself
             diverges (|lam_slow| -> inf) even though the sign is unambiguous
             and det(J) stays bounded. The A-Hurwitz gate above already
             rejects the genuinely singular case before this point.

        The slow flow is 1-D in theta and cannot oscillate, so this test
        does not see gamma-theta Hopf instabilities. That is correct, not a
        limitation -- see below.

        Why there is no fully-coupled criterion
        ---------------------------------------
        `dgamma_dt` is not a first-principles equation of motion: it is the
        rank-2 readout of the K-dimensional Glauber population dynamics
        (one n_k per visible target), obtained by differentiating
        gamma = sum_k n_k exp(i*neural_angle_k) and keeping ONLY the dn_k/dt
        term. The dropped term,

            -i * dtheta/dt * sum_k n_k * U'(theta_k) * exp(i*neural_angle_k),

        arises because the neural angles themselves move as the observer
        turns. It vanishes identically when dtheta/dt = 0, so every
        self-consistent equilibrium -- and this criterion, and the fast-block
        `_discrim_A` -- is unaffected. But OFF equilibrium the gamma-ODE is
        only valid under the timescale separation, which is exactly the
        assumption made here (and in the project preprint, whose navigational
        model is driven by the EQUILIBRIUM consensus gamma*, and in Sridhar et
        al. 2021 SI sec 1.7, whose Eq [15] likewise drops it and is used only
        at fixed target bearings).

        Consequently there is deliberately NO 'coupled' criterion. Taking the
        full 3x3 eigenvalues of `_coupled_jacobian` linearizes an incomplete
        equation and reports instabilities the model does not have: on the
        documented vonmises k=0.55 island it flagged 6 equilibria as
        Hopf-unstable (with an attracting limit cycle) where the exact
        population system is stable at every one. Nor can it be patched at the
        gamma level -- under a non-identity warp U the dropped term is not
        proportional to gamma (U' differs per target), so it is not a function
        of gamma at all.

        A genuine coupled analysis therefore requires the (K+1)-dimensional
        (n_1..n_K, theta) population system, where it also needs an explicit
        neural timescale tau_0: the verdict depends on kappa*tau_0, and the
        gamma-ODE implicitly assumes kappa*tau_0 = 2 (turning FASTER than
        neural relaxation), the opposite of the separation assumed everywhere
        else. This criterion is the tau_0 -> 0 limit, which is the dynamics
        `plot_walkers` and `_basin_destination` actually integrate.
        '''
        J = self._coupled_jacobian(gamma_star, focal_angle, focal_loc, h)
        A = J[:2, :2]
        # Fast (gamma) layer must be attracting for the slow reduction to be
        # meaningful: if A is not Hurwitz the branch h(theta) is not a stable
        # sheet. This gate also means det(A) > 0 below.
        if not np.all(np.real(np.linalg.eigvals(A)) < -tol):
            return False
        # Slow layer: sign(lam_slow) = sign(det J) (since det(A) > 0), computed
        # without the ill-conditioned A^{-1} of the Schur complement.
        return bool(np.linalg.det(J) < 0.0)


    def _discrim_A(self, gamma_star, focal_angle, focal_loc, h=1e-6,
                   tol=1e-8):
        '''Determines gamma-stability from the analytic 2x2 fast block (the
        free-energy Hessian H_Fhat) at a self-consistent equilibrium.

        gamma is stable iff H_Fhat is positive definite, which for a symmetric
        2x2 means BOTH the transverse curvature is positive (the classic
        A < 1 condition) AND det H_Fhat > 0. A < 1 alone is necessary but NOT
        sufficient: it is only the tangential diagonal entry and misses radial
        folds (H_rr < 0) and off-diagonal (R-Theta) saddles (det < 0). This is
        the complete fast-block test -- identical to the A-Hurwitz gate of
        _discrim_reduced for the cosine kernel -- but WITHOUT the slow
        heading-tracking (Schur) mode; use 'reduced' for that. See
        theory/free_energy_derivation.md sec 6.1.

        The analytic form below assumes the plain cosine kernel, which is
        what makes the flow a gradient flow. With `angle_distortion_nu` set to
        anything but 1 that structure is gone -- the fast block is no longer
        symmetric, so it is not the Hessian of anything -- and the block is
        instead differenced numerically out of `_coupled_jacobian` and tested
        for Hurwitz-ness. The two routes are the same test where both apply
        -- 0 verdict disagreements over 446 nu=1 equilibria spanning
        delta, circle and capsule targets -- the numerical one is simply
        not restricted to a gradient flow.

        Parameters
        ----------
        gamma_star : complex
            equilibrium gamma value at which to compute the Jacobian
        focal_angle : float
            the current heading (angle) of the observer. If None, use
            self.percep_model.focal_angle.
        focal_loc : array-like of length 2
            (x,y) location of the observer
        h : float, optional
            finite-difference step for the numerical block. Used only when
            `angle_distortion_nu` makes the kernel non-cosine.
        tol : float, optional
            Hurwitz margin for the numerical block: every eigenvalue must have
            real part < -tol. Used only in that same case.

        Returns
        -------
        True if stable, False if unstable
        '''

        if self._nu_active:
            J = self._coupled_jacobian(gamma_star, focal_angle, focal_loc, h)
            return bool(np.all(np.real(np.linalg.eigvals(J[:2, :2])) < -tol))

        Theta = np.angle(gamma_star)
        R = np.abs(gamma_star)
        neur_angles, rho = self.percep_model.get_neural_signals(focal_angle, focal_loc)
        with np.errstate(over='ignore'):
            # w_j = (beta/2) rho_j sech^2(beta R cos(Theta - theta_j)) >= 0 is
            # the per-target weight in the Cartesian free-energy Hessian
            # H_Fhat = I - sum_j w_j vhat_j vhat_j^T (gradient flow: fast
            # block A_block = -H_Fhat). Work in the frame rotated to gamma so
            # x = radial (R), y = tangential (arg gamma); det is rotation-
            # invariant. cc/ss are cos/sin of the target angle relative to
            # the consensus.
            w = (self.beta/2*rho
                 / np.cosh(self.beta*R*np.cos(Theta-neur_angles))**2)
            cc = np.cos(Theta - neur_angles)
            ss = np.sin(Theta - neur_angles)
            A = np.sum(w*ss**2)            # transverse: 1 - H_tt (the old scalar)
            H_rr = 1 - np.sum(w*cc**2)     # radial curvature
            H_rt = -np.sum(w*cc*ss)        # R-Theta coupling
            detH = H_rr*(1 - A) - H_rt**2  # det H_Fhat
        # Full gamma-stability = H_Fhat positive definite = transverse
        # curvature positive (A < 1) AND det > 0. Strict (matches the
        # A-Hurwitz gate of _discrim_reduced).
        return bool((A < 1) and (detH > 0))
